default:
    labels:
      duplicate: close
      wontfix: close
      invalid: close
      'merge when passing': merge
      'squash when passing': merge
      'rebase when passing': merge

    comments: []


    merges:
  - action: delete_branch
