language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  #- bundle exec htmlproofer ./_site --disable-external --check-favicon --check-html --assume_extension
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
