gems:
  - jemoji
  - jekyll-paginate
  - jekyll-time-to-read
  - jekyll-sitemap

title: "Valentino Urbano"
description: >
   iOS Developer, Swift, Writer, Husband

email: valentino@valentinourbano.com
#blog logo
logo: "/assets/images/df_logo.png"
# blog cover
cover: "/assets/images/logo_image.png"

name: 'Valentino Urbano'
author: 'Valentino Urbano'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://valeIT.github.io/"
baseurl: ""
twitter_handle: '@valentinourbano'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

social:
  - icon:	twitter
    url:	https://twitter.com/valentinourbano
    desc: Follow me on twitter
    share_url: 
    share_title: 
    share_link: 

  - icon: apple
    url:  /apps
    desc: Check out my apps
    share_url: 
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/valeIT/valeIT.github.io/
    desc:	This site is open source
    share_url:
    share_title:
    share_link:

kramdown:
  default_lang: swift

permalink: /:title.html

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"