plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-time-to-read
  - jekyll-sitemap
  - pagemaster

title: "Valentino Urbano"
description: >
  iOS Developer, Swift, Writer, Husband

email: valentino@valentinourbano.com
#blog logo
logo: "/assets/images/df_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/logo_image.png"

name: "Valentino Urbano"
author: "Valentino Urbano"
author_image: "/assets/images/author.png"
yearStart: "2012"

paginate: 5

url: "http://www.valentinourbano.com"
baseurl: ""
twitter_handle: "@valentinourbano"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-61742521-6

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/valentinourbano
    desc: Follow me on twitter
    share_url:
    share_title:
    share_link:

  - icon: github
    url: https://github.com/valeIT/valeIT.github.io/
    desc: This site is open source
    share_url:
    share_title:
    share_link:

kramdown:
  default_lang: swift

permalink: /:title.html

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# collections_dir: collections

collections:
  bestofmusic:
    output: true
    source: bestof/music.json
    id_key: id
    layout: bestof

exclude: [vendor]

future: false #do not allow posts from the future to be published...

assets:
  destination: "/assets"
  compression: true
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
