version: '3'

services:
  site:
    image: jekyll/jekyll:latest
    command: jekyll serve --livereload --incremental --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle